language: node_js

node_js:
- '8'

cache:
  directories:
  - node_modules

dist: trusty

jobs:
  include:
  - script: npm run lint
  - script:
    - npm run test
  - stage: Build
    script:
    - npm run build
